services:
  game-project:
    image: game-project
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/project/build
    develop:
      watch:
        - action: rebuild
          path: .